#!/usr/bin/env bash
#
# One-time installer for the standby database on the VPS. Run it ON the VPS
# as the deploy user (no root required):
#
#   bash /var/www/performancetracking/app/current/scripts/db/standby/install-on-vps.sh
#
# What it does (idempotent — safe to re-run):
#   1. Creates ~/mysql-standby with a memory-tuned MySQL 8 instance on :3307
#      (runs the mysqld binary from a copy in $HOME so AppArmor stays happy)
#   2. Registers it in pm2 as "mysql-standby" (auto-restart on crash)
#   3. Creates the app database + user on the standby, locked down to 127.0.0.1
#   4. Copies the sync daemon to ~/mysql-standby and registers it as "db-sync"
#   5. Runs the first sync primary → standby
#   6. Adds DB_STANDBY_* variables to backend/.env.production and restarts
#      the API so failover goes live
#   7. Adds "@reboot pm2 resurrect" to the crontab so pm2 apps (and the
#      standby) survive VPS reboots; verifies the nightly backup cron works
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
BACKEND_DIR="$APP_ROOT/backend"
ENV_FILE="${ENV_FILE:-$BACKEND_DIR/.env.production}"
STANDBY_HOME="$HOME/mysql-standby"
BIN="$STANDBY_HOME/bin/mysqld"
# NOTE: deliberately NOT named $PORT — backend/.env.production (sourced below)
# defines PORT=5001 for Express, which would silently retune the standby.
STANDBY_PORT=3307
PM2="$(command -v pm2)"

log() { echo "[standby-install] $*"; }

# ---------------------------------------------------------------- sanity ---
[ -f "$ENV_FILE" ] || { log "ERROR: env file not found: $ENV_FILE"; exit 1; }
[ -x /usr/sbin/mysqld ] || { log "ERROR: /usr/sbin/mysqld not found"; exit 1; }
[ -n "$PM2" ] || { log "ERROR: pm2 not in PATH"; exit 1; }
command -v node >/dev/null || { log "ERROR: node not in PATH"; exit 1; }

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a
: "${DB_NAME:?DB_NAME missing in $ENV_FILE}"
: "${DB_USER:?DB_USER missing in $ENV_FILE}"
: "${DB_PASSWORD:?DB_PASSWORD missing in $ENV_FILE}"

# ------------------------------------------------------- dirs + binaries ---
mkdir -p "$STANDBY_HOME/bin" "$STANDBY_HOME/data" "$STANDBY_HOME/tmp" "$STANDBY_HOME/log"
mkdir -p "$HOME/backups/standby-snapshots"
if [ ! -f "$BIN" ]; then
  log "copying mysqld binary (unconfined copy — avoids AppArmor datadir restrictions)"
  cp /usr/sbin/mysqld "$BIN"
  chmod 755 "$BIN"
fi

# ----------------------------------------------------------- config file ---
cat > "$STANDBY_HOME/my-standby.cnf" <<EOF
# Standby MySQL instance — generated by scripts/db/standby/install-on-vps.sh
# Memory-tuned to coexist with the primary mysqld + pm2 apps on this VPS.
[mysqld]
port=$STANDBY_PORT
bind-address=127.0.0.1
socket=$STANDBY_HOME/mysql.sock
datadir=$STANDBY_HOME/data
tmpdir=$STANDBY_HOME/tmp
pid-file=$STANDBY_HOME/mysqld.pid
log-error=$STANDBY_HOME/log/error.log
server-id=2001
basedir=/usr
lc_messages_dir=/usr/share/mysql
performance_schema=OFF
mysqlx=OFF
skip-name-resolve
innodb_buffer_pool_size=64M
innodb_redo_log_capacity=32M
max_connections=40
table_open_cache=200
open_files_limit=1024
event_scheduler=OFF

[client]
socket=$STANDBY_HOME/mysql.sock
port=$STANDBY_PORT
EOF

# ------------------------------------------------------------- initialize --
if [ ! -d "$STANDBY_HOME/data/mysql" ]; then
  log "initializing standby datadir (first run only)"
  "$BIN" --defaults-file="$STANDBY_HOME/my-standby.cnf" --initialize-insecure
fi

# -------------------------------------------------------- start via pm2 ----
if "$PM2" jlist 2>/dev/null | grep -qE '"name":\s*"mysql-standby"'; then
  log "mysql-standby already registered in pm2 — ensuring it is started"
  "$PM2" start mysql-standby >/dev/null 2>&1 || true
else
  log "starting standby instance under pm2"
  "$PM2" start "$BIN" --name mysql-standby --interpreter none --max-memory-restart 700M \
    -- --defaults-file="$STANDBY_HOME/my-standby.cnf"
fi

# ------------------------------------------------------------- readiness ---
# mysqladmin ping exits 0 as soon as the server accepts connections (even if
# the account check fails), which is exactly what we want pre-bootstrap.
ready=0
for _ in $(seq 1 120); do
  if [ -f "$STANDBY_HOME/.bootstrapped" ]; then
    if mysql --no-defaults -h127.0.0.1 -P"$STANDBY_PORT" -u"$DB_USER" -p"$DB_PASSWORD" -e "SELECT 1" >/dev/null 2>&1; then ready=1; break; fi
  else
    # NB: --no-defaults everywhere — ~/.my.cnf on this box points at the
    # PRIMARY and would silently redirect every client call.
    if mysqladmin --no-defaults --socket="$STANDBY_HOME/mysql.sock" -uroot ping >/dev/null 2>&1; then ready=1; break; fi
  fi
  sleep 1
done
[ "$ready" = "1" ] || { log "ERROR: standby did not become ready; see $STANDBY_HOME/log/error.log"; exit 1; }
log "standby is accepting connections on 127.0.0.1:$STANDBY_PORT"

# -------------------------------------------------------------- bootstrap --
if [ ! -f "$STANDBY_HOME/.bootstrapped" ]; then
  log "bootstrapping app user + database on standby"
  read -r CHARSET COLLATION < <(mysql --no-defaults -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" -e \
    "SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='$DB_NAME'" \
    -N 2>/dev/null || echo "utf8mb4 utf8mb4_0900_ai_ci")
  CHARSET="${CHARSET:-utf8mb4}"
  COLLATION="${COLLATION:-utf8mb4_0900_ai_ci}"
  PW_ESC="${DB_PASSWORD//\\/\\\\}"
  PW_ESC="${PW_ESC//\'/\\\'}"
  cat > "$STANDBY_HOME/bootstrap.sql" <<EOF
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET $CHARSET COLLATE $COLLATION;
CREATE USER IF NOT EXISTS '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$PW_ESC';
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$PW_ESC';
ALTER USER '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$PW_ESC';
ALTER USER '$DB_USER'@'localhost' IDENTIFIED BY '$PW_ESC';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'127.0.0.1';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
EOF
  mysql --no-defaults --socket="$STANDBY_HOME/mysql.sock" -uroot < "$STANDBY_HOME/bootstrap.sql" 2>/dev/null \
    || mysql --no-defaults --socket="$STANDBY_HOME/mysql.sock" -uroot -p"$DB_PASSWORD" < "$STANDBY_HOME/bootstrap.sql"
  # Lock the standby's root account down: auth_socket means only OS root can
  # use it (the app and the sync daemon only ever use the app user).
  if ! mysql --no-defaults --socket="$STANDBY_HOME/mysql.sock" -uroot \
       -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;" 2>/dev/null \
     && ! mysql --no-defaults --socket="$STANDBY_HOME/mysql.sock" -uroot -p"$DB_PASSWORD" \
       -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;" 2>/dev/null; then
    RANDPW="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 24)"
    if mysql --no-defaults --socket="$STANDBY_HOME/mysql.sock" -uroot \
         -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$RANDPW';" 2>/dev/null \
       || mysql --no-defaults --socket="$STANDBY_HOME/mysql.sock" -uroot -p"$DB_PASSWORD" \
         -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$RANDPW';" 2>/dev/null; then
      log "NOTE: auth_socket unavailable; standby root got a random password"
    else
      log "NOTE: could not alter standby root (no admin access) — skipping; app uses $DB_USER anyway"
    fi
  fi
  rm -f "$STANDBY_HOME/bootstrap.sql"
  touch "$STANDBY_HOME/.bootstrapped"
  log "bootstrap done (root account locked to auth_socket)"
fi

# ------------------------------------------------------- install the daemon
cp "$SCRIPT_DIR/sync-standby.js" "$STANDBY_HOME/sync-standby.js"
log "sync daemon copied to $STANDBY_HOME/sync-standby.js"

log "running first sync (primary → standby)"
node "$STANDBY_HOME/sync-standby.js" --once

if "$PM2" jlist 2>/dev/null | grep -qE '"name":\s*"db-sync"'; then
  log "db-sync already registered in pm2 — updating script copy"
  "$PM2" restart db-sync >/dev/null 2>&1 || true
else
  log "starting sync daemon under pm2"
  "$PM2" start "$STANDBY_HOME/sync-standby.js" --name db-sync --max-memory-restart 300M --time
fi
"$PM2" save

# ------------------------------------------------- phpMyAdmin two servers --
# Standalone helper so this step can also be run on its own.
if [ -d /home/feveneyasu/apps/phpmyadmin ]; then
  bash "$SCRIPT_DIR/pma-two-servers.sh" || log "WARN: phpMyAdmin config update failed (non-fatal)"
fi

# ------------------------------------------------------- app env + restart -
if grep -q '^DB_STANDBY_PORT=' "$ENV_FILE"; then
  log "DB_STANDBY_* already present in env file"
else
  cat >> "$ENV_FILE" <<EOF

# --- Standby database failover (installed by scripts/db/standby) ---
DB_STANDBY_HOST=127.0.0.1
DB_STANDBY_PORT=$STANDBY_PORT
DB_STANDBY_ENABLED=true
EOF
  log "added DB_STANDBY_* to $ENV_FILE"
fi
log "restarting perf-tracking-api to pick up failover config"
"$PM2" restart perf-tracking-api >/dev/null 2>&1 || log "WARN: could not restart perf-tracking-api automatically"

# ------------------------------------------------- boot persistence + crons
if ! crontab -l 2>/dev/null | grep -q 'pm2 resurrect'; then
  (crontab -l 2>/dev/null; echo "@reboot $PM2 resurrect >/dev/null 2>&1") | crontab -
  log "added @reboot pm2 resurrect to crontab (apps now survive reboots)"
fi
"$PM2" save >/dev/null 2>&1

# Nightly backup cron sanity: on MySQL 8.0.21+ mysqldump without
# --no-tablespaces fails for users without the PROCESS privilege, producing
# empty .sql.gz files. Detect and fix.
LATEST_BACKUP="$(ls -t "$HOME/backups"/vas-*.sql.gz 2>/dev/null | head -1 || true)"
if [ -n "$LATEST_BACKUP" ] && [ "$(stat -c%s "$LATEST_BACKUP")" -lt 1000 ]; then
  log "nightly backups look broken (empty .sql.gz) — adding --no-tablespaces to the cron line"
  crontab -l 2>/dev/null | sed 's/mysqldump --single-transaction --routines --triggers/mysqldump --single-transaction --routines --triggers --no-tablespaces --hex-blob/' | crontab -
  log "running a test backup now"
  mkdir -p "$HOME/backups"
  mysqldump --no-defaults --single-transaction --routines --triggers --no-tablespaces --hex-blob \
    -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" 2>/dev/null | gzip > "$HOME/backups/vas-test.sql.gz"
  log "test backup size: $(stat -c%s "$HOME/backups/vas-test.sql.gz") bytes"
fi

# ----------------------------------------------------------------- status --
echo
log "=========================== INSTALL COMPLETE ==========================="
log "pm2 status:"
"$PM2" ls | grep -E 'mysql-standby|db-sync|perf-tracking-api' || true
PRIMARY_TABLES=$(mysql --no-defaults -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" -N -e \
  "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$DB_NAME'" 2>/dev/null || echo '?')
STANDBY_TABLES=$(mysql --no-defaults -h127.0.0.1 -P"$STANDBY_PORT" -u"$DB_USER" -p"$DB_PASSWORD" -N -e \
  "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$DB_NAME'" 2>/dev/null || echo '?')
log "tables on primary=$PRIMARY_TABLES, standby=$STANDBY_TABLES"
log "sync log:    $STANDBY_HOME/log/sync.log"
log "failback marker (should be absent): $STANDBY_HOME/FAILOVER"
log "health check: curl -s http://127.0.0.1:5001/api/health  → should show dbTarget:primary"
